name: sim

on:
  push:
  pull_request:

jobs:
  icarus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Build
        run: iverilog -g2012 -o cache_tb.vvp cache_icarus.sv cache_tb_icarus.sv

      - name: Run
        run: vvp cache_tb.vvp

